kzl-linux and ubuntu: pacman scripts

diff --git a/kzl-linux/pacman/scripts/build b/kzl-linux/pacman/scripts/build
--- a/kzl-linux/pacman/scripts/build
+++ b/kzl-linux/pacman/scripts/build
@@ -18,7 +18,8 @@ BASH_LIB_DIR=${BASH_LIB_DIR:-"/home/kzl/LFS/bash/lib"}
 ################################################################################
 
 ### libraries
-source "$BASH_LIB_DIR/log.sh"
+source "$BASH_LIB_DIR"/log.sh
+source "$SCRIPT_DIR"/lib/pkglists.sh
 
 ### constants & variables
 VERSION="1.0"
@@ -26,380 +27,30 @@ VERSION="1.0"
 LOG_DIR="$HOME"/makepkg/log
 
 repo=
-repo_path="/home/.repository/$repo/$repo.db"
-build_only_updated=0
 stage=""
 single_package=""
-no_install=0
-no_clean=0
-no_check=0
-
-# preparation
-kzl_stage0_pkgs=(
-)
-
-# toolchain
-kzl_stage1_pkgs=(
-    ################################
-    # toolchain
-    ################################
-
-    ################
-    # filesystem
-    ################
-    iana-etc filesystem
-
-    ################
-    # glibc
-    ################
-    linux-api-headers
-    tzdata
-    glibc
-
-    ################
-    # binutils
-    ################
-    jansson
-    zlib
-    zstd
-    binutils
-
-    ################
-    # gcc
-    ################
-    gmp isl
-    mpfr mpc
-    gcc
-
-    ################################
-    tzdata glibc
-    jansson zlib zstd bc binutils
-    gmp isl mpfr mpc gcc
-    libtool
-)
-
-# base
-kzl_stage2_pkgs=(
-    ################################
-    # base
-    ################################
-
-    ################
-    # bash
-    ################
-    ncurses readline bash bash-completion
-
-    ################
-    # perl
-    ################
-    libxcrypt db gdbm perl
-
-    ################
-    # texinfo
-    ################
-    help2man texinfo
-
-    ################################
-    # other base-development
-    ################################
-    m4
-    autoconf automake autoconf-archive
-    bison
-    flex
-    ed bc
-    diffutils
-    patch
-    which
-    pkgconf
-
-    ################
-    # make
-    ################
-    libffi gc guile
-    make
-
-    ################
-    # gettext
-    ################
-    libunistring icu libxml2 gettext
-
-    ################
-    # ca-certificates & openssl
-    ################
-    libtasn1 p11-kit ca-certificates
-    openssl
-
-    ################
-    # python
-    ################
-    expat
-    e2fsprogs keyutils libedit lmdb cyrus-sasl openldap krb5 libtirpc libnsl
-    tcl sqlite
-    elfutils gdb valgrind
-    python
-
-    ################
-    # compression utils
-    ################
-    bzip2
-    pcre2 less gzip
-    xz
-    attr acl tar
-
-    ################
-    # utils
-    ################
-    grep
-    sed
-    libsigsegv gawk
-    libseccomp file
-    findutils
-
-    ################
-    # shadow
-    ################
-    swig libcap-ng audit
-    pam-config pam
-    shadow
-
-    ################
-    # coreutils
-    ################
-    libcap coreutils
-
-    ################
-    # curl
-    ################
-    brotli
-    libidn2
-    nghttp2
-    libgpg-error libgcrypt libxslt libpsl
-    libssh2
-    curl
-
-    ################
-    # llvm
-    ################
-    llvm-project
-
-    ################
-    # rust
-    ################
-    rust
-
-    ################
-    # util-linux
-    ################
-    thin-provisioning-tools argon2 libaio device-mapper json-c popt cryptsetup
-    util-linux
-
-    ################
-    # iptables
-    ################
-    libmnl libnfnetlink libnetfilter_conntrack
-    libnftnl
-    dbus libnl libpcap
-    iptables
-
-    ################
-    # systemd
-    ################
-    kbd
-    kmod
-    lz4
-    kexec-tools
-    nettle gnutls libmicrohttpd
-    gperf
-    rpcsvc-proto quota
-    systemd
-    util-linux dbus systemd
-
-    ################
-    # wget
-    ################
-    lzip
-    wget2
-
-    ################
-    # sudo
-    ################
-    sudo
-
-    ################
-    # pacman
-    ################
-    fakeroot
-    libassuan libksba npth pinentry gnupg gpgme
-    libarchive
-    pacman
-    pacman-contrib
-    arch-install-scripts
-
-    ################
-    # ps utils
-    ################
-    procps-ng
-    psmisc
-
-    ################
-    # ip utils
-    ################
-    iputils
-    iproute2
-
-    ################
-    # pciutils
-    ################
-    hwdata
-    pciutils
-
-    ################
-    # usbutils
-    ################
-    libusb
-    usbutils
-
-    ################
-    # cmake
-    ################
-    jsoncpp
-    libuv
-    rhash
-    cmake
-
-    ################
-    # man-db
-    ################
-    groff libpipeline
-    man-db
-
-    ################
-    # base
-    ################
-    base
-
-    ################
-    # linux-firmware
-    ################
-    linux-firmware
-    pahole
-)
-
-kzl_stage3_pkgs=(
-    ################
-    # shells
-    ################
-    pcre zsh
-    fish
-
-    ################
-    # utils
-    ################
-    openssh
-    nano
-    git
-
-    ################
-    # File system utils
-    ################
-    dosfstools
-    f2fs-tools
-    parted
-
-    ################
-    # dpkg
-    ################
-    libmd dpkg
-    debootstrap
-
-    ################
-    # iso
-    ################
-    cpio dracut
-    libburn libisofs libisoburn
-    mtools
-
-    ################
-    # Wireless Network
-    ################
-    iw wpa_supplicant
-    wireless-regdb
-
-    ################
-    # samba
-    ################
-    liburing
-    samba
-
-    ################
-    # rsync
-    ################
-    xxhash
-    rsync
-
-    ################
-    # tmux
-    ################
-    libevent tmux
-
-    ################
-    # texlive
-    ################
-    libpng
-    glib2 shared-mime-info
-    fontconfig freetype2 lzo pixman cairo
-    graphite
-    gobject-introspection
-    harfbuzz freetype2
-    libpaper
-    nasm libjpeg-turbo
-    libtiff lcms2 openjpeg
-    ghostscript
-    gd
-    zziplib
-    texlive
-
-    ################
-    # node
-    ################
-    # c-ares
-    # node
-
-    ################
-    # other libraries
-    ################
-    openblas
-    libpciaccess hwloc openmpi boost
-    ################
-    # other utils
-    ################
-    # tree
-    # minicom
-    # dfu-util
-    # smartmontools
-    aria2
-    # libtorrent-rasterbar qbittorrent
-)
+declare -i build_only_updated=0
+declare -i install=0
+declare -i no_clean=0
+declare -i no_check=0
 
 ### functions
 prepare() {
     info "Removing pacman cache and database..."
     (yes yes || :) | sudo pacman -Scc >/dev/null 2>&1
-
-    if [[ ! -f "$repo_path" ]]; then
-        info "Creating empty repo \"$repo\"..."
-        updaterepo -t "$repo" >/dev/null 2>&1
-    fi
     info "Done"
+
+    if [[ ! -e "$repo_path" ]]; then
+        info "Creating empty repo \"$repo\" on \"$repo_path\"..."
+        updaterepo -t "$repo" >/dev/null 2>&1
+        info "Done"
+    fi
 
     info "Synchronizing package databases..."
     (yes yes || :) | sudo pacman -Syy >/dev/null 2>&1
-
-    if [[ -d "$LOG_DIR" ]]; then
-        info "Creating log directory..."
-        mkdir -p -- "$LOG_DIR"
-    fi
     info "Done"
+
+    mkdir -p -- "$LOG_DIR"
 }
 
 get_pkgbase() {
@@ -434,63 +85,70 @@ build() {
 
     # update pkgbuild
     info "Updating PKGBUILD..."
-    _updated=0
-    updatepkg >"$_log" 2>&1 || _updated=$?
+    updatepkg >"$_log" 2>&1
+    _updated=$?
 
     _cleanbuild='C'
     if (( $_updated == 255 )); then
-        warning "Current version is newer"
+        warn "Current version is newer"
         _updated=0
     elif (( $_updated == 0 )); then
-        info "PKGBUILD is already up to date"
+        info "No update for PKGBUILD"
     elif (( $_updated == 1 )); then
         info "Package \"$_pkgbase\" is updated to new version"
         _cleanbuild='e'
     elif (( $_updated == 2 )); then
-        warning "PKGUPDATE does not exist"
-    elif (( $_updated >= 3 )); then
-        error "Cannot update the PKGBUILD (error code: $_updated)" 4
+        error "PKGBUILD does not exist" 5
+    elif (( $_updated == 3 )); then
+        warn "PKGUPDATE does not exist"
+    elif (( $_updated >= 4 )); then
+        error "Cannot update the PKGBUILD (error code: $_updated)" 5
     else
-        error "Unknown \`updatepkg\` result" 6
+        error "Unknown \`updatepkg\` result" 5
     fi
+    info "Done"
 
     if (( $build_only_updated > 0 )) && (( $_updated == 0 )); then
         info "Package \"$_pkgbase\" is already the latest version, will not build (-u, --build-only-updated)."
-    else
-        info "Building package..."
-
-        # if package is up to date, then update the "pkgrel"
-        if (( $_updated == 0 )); then
-            # update "pkgrel"
-            current_pkgrel=$(cat PKGBUILD | grep -oP 'pkgrel=\K\d+$')
-            new_pkgrel=$(($current_pkgrel + 1))
-            sed -i "/^pkgrel=/s/$current_pkgrel/$new_pkgrel/" PKGBUILD
-        fi
-
-        _no_check=''
-        if (( $no_check > 0 )); then
-            _no_check='--nocheck'
-        fi
-        _clean=''
-        if (( $no_clean <= 0 )); then
-            _clean='--clean'
-        fi
-        # calling makepkg without `-C` since updatepkg already removed existing `$srcdir/`
-        makepkg -sr"$_cleanbuild"f "$_clean" "$_no_check" --noconfirm >>"$_log" 2>&1
-
-        info "Updating repo..."
-        updaterepo -t "$repo" >>"$_log" 2>&1
-
-        if (( $no_install <= 0 )); then
-            info "Installing package..."
-            # (yes yes || :) | sudo pacman -Sddy --overwrite "*" $_pkgname --config ${pacman_conf}
-            (yes yes || :) | sudo pacman -Sy $_pkgname >>"$_log" 2>&1
-        fi
+        return
     fi
+
+    info "Building package..."
+
+    # if package is up to date, then update the "pkgrel"
+    if (( $_updated == 0 )); then
+        # update "pkgrel"
+        current_pkgrel=$(cat PKGBUILD | grep -oP 'pkgrel=\K\d+$')
+        new_pkgrel=$(($current_pkgrel + 1))
+        sed -i "/^pkgrel=/s/$current_pkgrel/$new_pkgrel/" PKGBUILD
+    fi
+
+    _no_check=''
+    if (( $no_check > 0 )); then
+        _no_check='--nocheck'
+    fi
+    _clean=''
+    if (( $no_clean <= 0 )); then
+        _clean='--clean'
+    fi
+    # calling makepkg without `-C` since updatepkg already removed existing `$srcdir/`
+    makepkg -sr"$_cleanbuild"f "$_clean" "$_no_check" --noconfirm >>"$_log" 2>&1
+
+    info "Updating repo..."
+    updaterepo -t "$repo" >>"$_log" 2>&1
+
+    if (( $install > 0 )); then
+        info "Installing package..."
+        # (yes yes || :) | sudo pacman -Sddy --overwrite "*" $_pkgname --config ${pacman_conf}
+        (yes yes || :) | sudo pacman -Sy $_pkgname >>"$_log" 2>&1
+    fi
+
+    info "Done"
 }
 
 usage() {
     cat <<EOF
+
 Usage: $SCRIPT_NAME -V | --version
 Usage: $SCRIPT_NAME -h | --help
 Usage: $SCRIPT_NAME -r <repo> -s <stage> [ -n ] [ -u ] [ --no-clean ] [ --no-check ]
@@ -501,7 +159,7 @@ Usage: $SCRIPT_NAME -r <repo> -p <pkg> [ -n ] [ -u ] [ --no-clean ] [ --no-check
     -r, --repo                  target repository (kzl, testing, ...)
     -s, --stage                 stage (0, 1(default), 2, 3)
     -p, --package               build single package
-    -n, --no-install            do not install the package after building
+    -i, --install               install the package after building
     -u, --build-only-updated    build the package only if the PKGBUILD is updated
     --no-clean                  skip cleaning up work files after build
     --no-check                  do not run the check() function in the PKGBUILD
@@ -509,7 +167,7 @@ Usage: $SCRIPT_NAME -r <repo> -p <pkg> [ -n ] [ -u ] [ --no-clean ] [ --no-check
 EOF
 }
 
-################################################################
+################################################################################
 
 while (($# > 0)); do
     case "$1" in
@@ -523,20 +181,20 @@ while (($# > 0)); do
         ;;
     -s|--stage)
         if [[ -n "$single_package" ]]; then
-            error "Cannot use -s | --stage together with -p | --package" 5
+            error "Cannot use -s | --stage together with -p | --package" 2
         fi
         shift
         stage="$1"
         ;;
     -p|--package)
         if [[ -n "$stage" ]]; then
-            error "Cannot use -p | --package together with -s | --stage" 5
+            error "Cannot use -p | --package together with -s | --stage" 2
         fi
         shift
         single_package="$1"
         ;;
-    -n|--no-install)
-        no_install=1
+    -i|--install)
+        install=1
         ;;
     -u|--build-only-updated)
         build_only_updated=1
@@ -549,18 +207,16 @@ while (($# > 0)); do
         ;;
     *)
         usage
-        error "Unknown option: \"$1\"" 1
+        error "Unknown option: \"$1\"" 255
         ;;
     esac
     shift
 done
 
-prologue
-
-case $repo in
-    kzl)
+case "$repo" in
+    core)
         if [[ -n "$stage" ]]; then
-            case $stage in
+            case "$stage" in
             0)
                 updaterepo --clear -t "$repo"
                 pkgs=("${kzl_stage0_pkgs[@]}")
@@ -575,10 +231,13 @@ case $repo in
                 pkgs=("${kzl_stage3_pkgs[@]}")
                 ;;
             *)
-                error "Unknown stage \"$stage\"" 2
+                error "Unknown stage \"$stage\"" 4
                 ;;
             esac
         fi
+        ;;
+    ubuntu)
+        pkgs=("${ubuntu_pkgs[@]}")
         ;;
     *)
         error "Unknown repo name \"$repo\"" 3
@@ -586,30 +245,37 @@ case $repo in
 esac
 log_blue "Building stage $stage ($(date +%H:%M:%S))..."
 
+repo_path="/home/.repository/$repo/$repo.db.tar.zst"
+
+################################################################################
+
+prologue
 
 prepare
-
 if [[ -n "$single_package" ]]; then
     # Build a single package
+    __pkg_start_time__=$(date +%s)
     log_magenta "Building $single_package ($(date +%H:%M:%S))..."
     build "$single_package"
+    __pkg_end_time__=$(date +%s)
+    __pkg_total_time__=$(($__pkg_end_time__ - $__pkg_start_time__))
+    log_cyan "$single_package: $(date -d@$__pkg_total_time__ -u +%H:%M:%S) ($(date +%H:%M:%S))"
 else
     for p in ${pkgs[@]}; do
-        __pkg_start_time__=$(date +%s)
         log_magenta "Building $p ($(date +%H:%M:%S))..."
-        build $p
+        __pkg_start_time__=$(date +%s)
+        build "$p"
         __pkg_end_time__=$(date +%s)
         __pkg_total_time__=$(($__pkg_end_time__ - $__pkg_start_time__))
-        echo -e "\e[1;32m$p: $(date -d@$__pkg_total_time__ -u +%H:%M:%S) ($(date +%H:%M:%S))\e[0m"
+        log_cyan "$p: $(date -d@$__pkg_total_time__ -u +%H:%M:%S) ($(date +%H:%M:%S))"
     done
 fi
 
 epilogue
 
 ### error codes
-# 1: unknown option
-# 2: unknown stage
-# 3: unknown repo
-# 4: cannot update the PKGBUILD
-# 5: cannot use -s | --stage together with -p | --package
-# 6: unknown `updatepkg` result
+# 2: cannot use -s | --stage together with -p | --package
+# 3: unknown repo name
+# 4: unknown stage
+# 5: cannot update the PKGBUILD
+# 255: unknown option
diff --git a/kzl-linux/pacman/scripts/updatepkg b/kzl-linux/pacman/scripts/updatepkg
--- a/kzl-linux/pacman/scripts/updatepkg
+++ b/kzl-linux/pacman/scripts/updatepkg
@@ -3,59 +3,52 @@
 # updatepkg
 #
 
-script_name="$(basename "${0}")"
+set -e
+set -u
+set -o pipefail
+# set -x
 
-cleanbuild=1
-increase=0
+umask 0022
 
-################################################################
+SCRIPT_NAME="$(basename "$0")"
+SCRIPT_PATH="$(readlink -f "$0")"
+SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
+BASH_LIB_DIR=${BASH_LIB_DIR:-"/home/kzl/LFS/bash/lib"}
 
-# Show an INFO message
-# $1: message string
-info() {
-    local _msg="$1"
-    printf '\033[0;32m[%s] INFO: %s\033[0m\n' "$script_name" "$_msg"
-}
+################################################################################
 
-# Show a WARNING message
-# $1: message string
-warning() {
-    local _msg="$1"
-    printf '\033[0;33m[%s] WARNING: %s\033[0m\n' "$script_name" "$_msg" >&2
-}
+### libraries
+source "$BASH_LIB_DIR"/log.sh
+# source "$BASH_LIB_DIR"/util.sh
+# source "$BASH_LIB_DIR"/chroot.sh
 
-# Show an ERROR message then exit with status
-# $1: message string
-# $2: exit code number (with 0 does not exit)
-error() {
-    local _msg="$1"
-    local _error="$2"
-    printf '\033[0;31m[%s] ERROR: %s\033[0m\n' "$script_name" "$_msg" >&2
-    if [[ "$_error" -gt 0 ]]; then
-        exit "$_error"
-    fi
-}
+### constants & variables
+PKGBUILDDIR=$(pwd)
 
+declare -i cleanbuild=1
+declare -i increase=0
+
+### functions
 have_function() {
 	declare -f "$1" >/dev/null
 }
 
 usage() {
-    local _usage="
-updatepkg (kzl-linux)
+    cat <<EOF
 
 Update the \`pkgver\` of PKGBUILD
 
-Usage: updatepkg [ -n ] [ -i ]
+Usage: $SCRIPT_NAME -h | --help
+Usage: $SCRIPT_NAME [ -n ] [ -i ]
 
     -h, --help                  Display this help message and exit
-    -n, --no-cleanbuild         Do not remove "\$srcdir/" dir before updating PKGBUILD
-    -i, --increase-pkgrel       Increase "\$pkgrel" by 1
-"
-    echo "$_usage"
+    -n, --no-cleanbuild         Do not remove "\$srcdir/" dir before updating PKGBUILD (default: remove)
+    -i, --increase-pkgrel       Increase "\$pkgrel" by 1 (default: no increase)
+
+EOF
 }
 
-################################################################
+################################################################################
 
 while (($# > 0)); do
     case "$1" in
@@ -71,40 +64,37 @@ while (($# > 0)); do
         ;;
     *)
         usage
-        error "Unknown option: \"$1\"" 1
+        error "Unknown option: \"$1\"" 255
         ;;
     esac
     shift
 done
 
-set -e
-set -o pipefail
-set -u
-# set -x
+################################################################################
 
-#
-if [[ ! -f PKGBUILD ]]; then
+if [[ ! -f "PKGBUILD" ]]; then
    error 'PKGBUILD does not exist.' 2
 fi
 
-if [[ -f "/etc/makepkg.conf" ]]; then
-    . /etc/makepkg.conf
-elif [[ -f "/usr/local/etc/makepkg.conf" ]]; then
-    . /usr/local/etc/makepkg.conf
-else
-    error 'makepkg.conf NOT found.' 5
+if [[ ! -f "PKGUPDATE" ]]; then
+    error "PKGUPDATE does not exist." 3
 fi
-source PKGBUILD
-PKGBUILDDIR=$(pwd)
 
-if [[ ! -f PKGUPDATE ]]; then
-    error "PKGUPDATE does not exist." 2
+if [[ -f "/etc/makepkg.conf" ]]; then
+    source /etc/makepkg.conf
+elif [[ -f "/usr/local/etc/makepkg.conf" ]]; then
+    source /usr/local/etc/makepkg.conf
+else
+    error 'makepkg.conf NOT found' 4
 fi
+
+source PKGBUILD
 
 unset new_version current_version pre_update post_update
 source PKGUPDATE || :
+
 if [[ -z "$new_version" ]]; then
-    error 'Cannot get new version.' 6
+    error 'Cannot get new version' 5
 fi
 info "New pkgver is $new_version"
 current_version=${current_version:-$(grep -oP 'pkgver=\K.+$' PKGBUILD | sed 's/.g.*//')}
@@ -115,49 +105,53 @@ info "Current pkgrel is $current_pkgrel"
 # run pre_update
 if have_function 'pre_update'; then
     info "running pre_update()..."
-    pre_update || error "\`pre_update\` error" 4
+    pre_update || error "\`pre_update\` error" 6
     cd "$PKGBUILDDIR"
 fi
 
 result=$(vercmp $new_version $current_version)
-if [[ $result -eq 1 ]]; then
+if (( $result == 1 )); then
     info "PKGBUILD updated: $current_version => $new_version"
     sed -i "/^pkgver=/s/$current_version/$new_version/" PKGBUILD
     sed -i "/^pkgrel=/s/$current_pkgrel/1/" PKGBUILD
     pkgver=$new_version
     info "running updpkgsums..."
-    updpkgsums || error "\`updpkgsums\` error" 2
+    updpkgsums || error "\`updpkgsums\` error" 7
     # force cleanbuild
     cleanbuild=1
-elif [[ $result -eq 0 ]]; then
+elif (( $result == 0 )); then
     info "PKGBUILD is up to date."
     if [[ $increase -gt 0 ]]; then
         info "increase pkgrel..."
         new_pkgrel=$((current_pkgrel + 1))
         sed -i "/^pkgrel=/s/$current_pkgrel/$new_pkgrel/" PKGBUILD
     fi
-elif [[ $result -eq -1 ]]; then
-    warning "Current version is newer."
+elif (( $result == -1 )); then
+    warn "Current version is newer"
 else
-    error "Unknown \`vercmp\` result." 7
+    error "Unknown \`vercmp\` result" 8
 fi
 
 if [[ $cleanbuild -gt 0 ]]; then
-    makepkg -Cdo || error "\`makepkg -o\` error" 3
+    makepkg -Cdo || error "\`makepkg -o\` error" 9
 else
-    makepkg -do || error "\`makepkg -o\` error" 3
+    makepkg -do || error "\`makepkg -o\` error" 9
 fi
 # run post_update
 info "running post_update()..."
-post_update || error "\`post_update\` error" 4
+post_update || error "\`post_update\` error" 10
 
-# -1: current version is newer
+### error codes
+# 255: current version is newer
 # 0: no update
 # 1: updated
-# 2: PKGUPDATE does not exist
-# 3: makepkg -o error
-# 4: pre_update or post_update error
-# 5: makepkg.conf not found
-# 6: cannot get new version
-# 7: unknown `vercmp` result
+# 2: PKGBUILD does not exist
+# 3: PKGUPDATE does not exist
+# 4: makepkg.conf NOT found
+# 5: cannot get new version
+# 6: pre_update error
+# 7: updpkgsums error
+# 8: unknown vercmp result
+# 9: makepkg error
+# 10: post_update error
 exit $result
