kzl-linux: pacman scripts

diff --git a/kzl-linux/pacman/scripts/build b/kzl-linux/pacman/scripts/build
--- a/kzl-linux/pacman/scripts/build
+++ b/kzl-linux/pacman/scripts/build
@@ -85,28 +85,29 @@ build() {
     # update pkgbuild
     if (( $updatepkg > 0 )); then
         info "Updating PKGBUILD..."
-        updatepkg --syncdeps -i >> "$_log" 2>&1 || _updated=$?
+        updatepkg --syncdeps >> "$_log" 2>&1 || _updated=$?
         _cleanbuild='-e'
 
         if (( $_updated == 255 )); then
-            warn "Current version is newer"
+            warn "  Current version is newer"
         elif (( $_updated == 0 )); then
             info "  No update for PKGBUILD"
         elif (( $_updated == 1 )); then
             info "  Package \"$_pkgbase\" is updated to new version"
+            updatepkg -I >> "$_log" 2>&1
         elif (( $_updated == 2 )); then
-            error "PKGBUILD does not exist" 5
+            error "  PKGBUILD does not exist" 5
         elif (( $_updated == 3 )); then
-            warn "PKGUPDATE does not exist"
+            warn "  PKGUPDATE does not exist"
             _cleanbuild='-C'
         elif (( $_updated >= 4 )); then
-            error "Cannot update the PKGBUILD (error code: $_updated)" 5
+            error "  Cannot update the PKGBUILD (error code: $_updated)" 5
         else
-            error "Unknown \`updatepkg\` result" 5
+            error "  Unknown \`updatepkg\` result" 5
         fi
 
         if (( $updated_only > 0 )) && (( $_updated == 0 || $_updated == 255 )); then
-            info "Package \"$_pkgbase\" is already the latest version, will not build (-u, --build-only-updated)."
+            info "  Package \"$_pkgbase\" is already the latest version, will not build (-u, --build-only-updated)."
             return
         fi
         info "Done"
@@ -219,9 +220,9 @@ if [[ -n "$single_package" ]]; then
         error "Cannot use -s | --stage together with -p | --package" 2
     fi
 else
-    stage=${stage:-1}
     case "$repo" in
         kzl)
+            stage=${stage:-1}
             case "$stage" in
             0)
                 # updaterepo --clear -r "$repo"
diff --git a/kzl-linux/pacman/scripts/updatepkg b/kzl-linux/pacman/scripts/updatepkg
--- a/kzl-linux/pacman/scripts/updatepkg
+++ b/kzl-linux/pacman/scripts/updatepkg
@@ -29,6 +29,7 @@ PKGBUILDDIR="$(pwd)"
 syncdeps='-d'
 cleanbuild='-C'
 declare -i increase=0
+declare -i increase_only=0
 
 ### functions
 have_function() {
@@ -38,17 +39,19 @@ have_function() {
 
 
 usage() {
-    cat <<EOF
+    cat << EOF
 
 Update the \`pkgver\` of PKGBUILD
 
 Usage: $SCRIPT_NAME -h | --help
-Usage: $SCRIPT_NAME [ -n ] [ -i ]
+Usage: $SCRIPT_NAME [ -s ] [ -n ] [ -i ]
+Usage: $SCRIPT_NAME -I
 
     -h, --help                  Display this help message and exit
     -s, --syncdeps              Install missing dependencies with pacman (default: no install)
     -n, --no-cleanbuild         Do not remove "\$srcdir/" dir before updating PKGBUILD (default: remove)
     -i, --increase-pkgrel       Increase "\$pkgrel" by 1 (default: no increase)
+    -I, --increase-pkgrel-only  Increase "\$pkgrel" by 1 only (implies \`-i\`; default: no increase)
 
 EOF
 }
@@ -61,7 +64,7 @@ while (( $# > 0 )); do
         usage
         exit 0
         ;;
-    -s | --syncdeps)
+    -s|--syncdeps)
         syncdeps='-sr'
         ;;
     -n|--no-cleanbuild)
@@ -69,6 +72,10 @@ while (( $# > 0 )); do
         ;;
     -i|--increase-pkgrel)
         increase=1
+        ;;
+    -I|--increase-pkgrel-only)
+        increase=1
+        increase_only=1
         ;;
     *)
         usage
@@ -80,14 +87,28 @@ done
 
 ################################################################################
 
+# PKGBUILD
 if [[ ! -f "PKGBUILD" ]]; then
    error 'PKGBUILD does not exist.' 2
 fi
+source PKGBUILD
+current_version=$(grep -oP 'pkgver=\K.+$' PKGBUILD | sed 's/.g\.*//')
+info "Current pkgver is $current_version"
+current_pkgrel=$(grep -oP 'pkgrel=\K\d+$' PKGBUILD)
+info "Current pkgrel is $current_pkgrel"
 
+# PKGUPDATE
 if [[ ! -f "PKGUPDATE" ]]; then
     error "PKGUPDATE does not exist." 3
 fi
+unset new_version current_version pre_update post_update
+source PKGUPDATE || :
+if [[ -z "$new_version" ]]; then
+    error 'Cannot get new version' 5
+fi
+info "New pkgver is $new_version"
 
+# makepkg.conf
 if [[ -f "/etc/makepkg.conf" ]]; then
     . /etc/makepkg.conf
 elif [[ -f "/usr/local/etc/makepkg.conf" ]]; then
@@ -96,36 +117,7 @@ else
     error 'makepkg.conf NOT found' 4
 fi
 
-source PKGBUILD
-
-unset new_version current_version pre_update post_update
-source PKGUPDATE || :
-
-if [[ -z "$new_version" ]]; then
-    error 'Cannot get new version' 5
-fi
-info "New pkgver is $new_version"
-current_version=${current_version:-$(grep -oP 'pkgver=\K.+$' PKGBUILD | sed 's/.g.*//')}
-info "Current pkgver is $current_version"
-current_pkgrel=$(grep -oP 'pkgrel=\K\d+$' PKGBUILD)
-info "Current pkgrel is $current_pkgrel"
-
-# receive key id
-if (( ${#validpgpkeys[@]} )); then
-    if ! gpg --list-keys --with-colons "${validpgpkeys[@]}" >/dev/null 2>&1; then
-        # gpg --keyserver "$PGP_KEY_SERVER" --recv-keys "${validpgpkeys[@]}" || error "\`gpg --recv-keys\` error" 11
-        gpg --recv-keys "${validpgpkeys[@]}" || error "\`gpg --recv-keys\` error" 11
-    fi
-fi
-
-# run pre_update
-if have_function 'pre_update'; then
-    info "Running pre_update()..."
-    pre_update || error "\`pre_update\` error" 6
-    cd "$PKGBUILDDIR"
-    info "Done"
-fi
-
+# update `pkgver` and `pkgrel`
 result=$(vercmp $new_version $current_version)
 if (( $result == 1 )); then
     info "PKGBUILD updated: $current_version => $new_version"
@@ -143,11 +135,32 @@ elif (( $result == 0 )); then
         info "Increase pkgrel..."
         new_pkgrel=$(($current_pkgrel + 1))
         sed -i "/^pkgrel=/s/$current_pkgrel/$new_pkgrel/" PKGBUILD
+        info "New pkgrel is $new_pkgrel"
+        if (( $increase_only > 0 )); then
+            exit $result
+        fi
     fi
 elif (( $result == -1 )); then
     warn "Current version is newer"
 else
+else
     error "Unknown \`vercmp\` result" 8
+fi
+
+# receive key id
+if (( ${#validpgpkeys[@]} )); then
+    if ! gpg --list-keys --with-colons "${validpgpkeys[@]}" > /dev/null 2>&1; then
+        # gpg --keyserver "$PGP_KEY_SERVER" --recv-keys "${validpgpkeys[@]}" || error "\`gpg --recv-keys\` error" 11
+        gpg --recv-keys "${validpgpkeys[@]}" || error "\`gpg --recv-keys\` error" 11
+    fi
+fi
+
+# run pre_update
+if have_function 'pre_update'; then
+    info "Running pre_update()..."
+    pre_update || error "\`pre_update\` error" 6
+    cd "$PKGBUILDDIR"
+    info "Done"
 fi
 
 info "Running \`makepkg -o\`..."
