kzl-linux: scripts

diff --git a/kzl-linux/pacman/scripts/build b/kzl-linux/pacman/scripts/build
--- a/kzl-linux/pacman/scripts/build
+++ b/kzl-linux/pacman/scripts/build
@@ -23,9 +23,10 @@ source "$BASH_LIB_DIR/log.sh"
 ### constants & variables
 VERSION="1.0"
 
-repo=kzl
-log_dir=~/makepkg/log
-repo_dir=/home/.repository/$repo
+LOG_DIR="$HOME"/makepkg/log
+
+repo=
+repo_path="/home/.repository/$repo/$repo.db"
 build_only_updated=0
 stage=""
 single_package=""
@@ -381,125 +382,122 @@ kzl_stage3_pkgs=(
 )
 
 ### functions
+
 prepare() {
     info "Removing pacman cache and database..."
-    (yes yes || :) | sudo pacman -Scc > /dev/null 2>&1
+    (yes yes || :) | sudo pacman -Scc >/dev/null 2>&1
 
-    if [ ! -f /home/.repository/$repo/$repo.db ]; then
+    if [[ ! -f "$repo_path" ]]; then
         info "Creating empty repo \"$repo\"..."
-        updaterepo -t $repo > /dev/null 2>&1
+        updaterepo -t "$repo" >/dev/null 2>&1
     fi
-    info "Synchronizing package databases..."
-    (yes yes || :) | sudo pacman -Syy > /dev/null 2>&1
+    info "Done"
 
-    if [ -d "$log_dir" ]; then
+    info "Synchronizing package databases..."
+    (yes yes || :) | sudo pacman -Syy >/dev/null 2>&1
+
+    if [[ -d "$LOG_DIR" ]]; then
         info "Creating log directory..."
-        mkdir -p "$log_dir"
+        mkdir -p -- "$LOG_DIR"
     fi
+    info "Done"
 }
 
 get_pkgbase() {
     local _pkgbase
-    case $1 in
+    case "$1" in
         device-mapper)
             _pkgbase=lvm2
             ;;
         *)
-            _pkgbase=$1
+            _pkgbase="$1"
             ;;
     esac
     echo "$_pkgbase"
 }
 
 build() {
-    local _pkgbase
-    local _pkgname
-    local _updated
+    local _pkgname="$1"
+    local _pkgbase=$(get_pkgbase $_pkgname)
+    local _log
+    local -i _updated
     local _cleanbuild
     local _clean
     local _no_check
-    local _log
 
-    _pkgname=$1
-    _pkgbase=$(get_pkgbase $_pkgname)
-    if [ -n "$stage" ]; then
-        _log="$log_dir"/$_pkgbase.stage$stage.log
+    if [[ -n "$stage" ]]; then
+        _log="$LOG_DIR"/$_pkgbase.stage$stage.log
     else
-        _log="$log_dir"/$_pkgbase.log
+        _log="$LOG_DIR"/$_pkgbase.log
     fi
 
-    # remove existing log
-    if [ -f $_log ]; then
-        rm -- $_log
-    fi
-
-    cd $ROOTDIR/pkgbuilds/$repo/$_pkgbase
+    cd "$ROOTDIR/pkgbuilds/$repo/$_pkgbase"
 
     # update pkgbuild
     info "Updating PKGBUILD..."
     _updated=0
-    updatepkg >> $_log 2>&1 || _updated=$?
+    updatepkg >"$_log" 2>&1 || _updated=$?
 
     _cleanbuild='C'
-    if [ "$_updated" -eq 255 ]; then
-        warning "Current version is newer."
+    if (( $_updated == 255 )); then
+        warning "Current version is newer"
         _updated=0
-    elif [ "$_updated" -eq 0 ]; then
-        info "PKGBUILD is already up to date."
-    elif [ "$_updated" -eq 1 ]; then
-        info "Package \"$_pkgbase\" is updated to new version."
+    elif (( $_updated == 0 )); then
+        info "PKGBUILD is already up to date"
+    elif (( $_updated == 1 )); then
+        info "Package \"$_pkgbase\" is updated to new version"
         _cleanbuild='e'
-    elif [ "$_updated" -eq 2 ]; then
-        warning "PKGUPDATE does not exist."
-    elif [ "$_updated" -ge 3 ]; then
-        error "Cannot update the PKGBUILD (error code: $_updated)." 4
+    elif (( $_updated == 2 )); then
+        warning "PKGUPDATE does not exist"
+    elif (( $_updated >= 3 )); then
+        error "Cannot update the PKGBUILD (error code: $_updated)" 4
     else
-        error "Unknown \`updatepkg\` result." 6
+        error "Unknown \`updatepkg\` result" 6
     fi
 
-    if [ "$build_only_updated" -gt 0 ] && [ "$_updated" -eq 0 ]; then
+    if (( $build_only_updated > 0 )) && (( $_updated == 0 )); then
         info "Package \"$_pkgbase\" is already the latest version, will not build (-u, --build-only-updated)."
     else
         info "Building package..."
 
         # if package is up to date, then update the "pkgrel"
-        if [ "$_updated" -eq 0 ]; then
+        if (( $_updated == 0 )); then
             # update "pkgrel"
             current_pkgrel=$(cat PKGBUILD | grep -oP 'pkgrel=\K\d+$')
-            new_pkgrel=$((current_pkgrel + 1))
+            new_pkgrel=$(($current_pkgrel + 1))
             sed -i "/^pkgrel=/s/$current_pkgrel/$new_pkgrel/" PKGBUILD
         fi
 
         _no_check=''
-        if [ "$no_check" -gt 0 ]; then
+        if (( $no_check > 0 )); then
             _no_check='--nocheck'
         fi
         _clean=''
-        if [ "$no_clean" -le 0 ]; then
+        if (( $no_clean <= 0 )); then
             _clean='--clean'
         fi
         # calling makepkg without `-C` since updatepkg already removed existing `$srcdir/`
-        makepkg -sr"$_cleanbuild"f $_clean $_no_check --noconfirm >> $_log 2>&1
+        makepkg -sr"$_cleanbuild"f "$_clean" "$_no_check" --noconfirm >>"$_log" 2>&1
 
         info "Updating repo..."
-        updaterepo -t $repo >> $_log 2>&1
+        updaterepo -t "$repo" >>"$_log" 2>&1
 
-        if [ "$no_install" -le 0 ]; then
+        if (( $no_install <= 0 )); then
             info "Installing package..."
             # (yes yes || :) | sudo pacman -Sddy --overwrite "*" $_pkgname --config ${pacman_conf}
-            (yes yes || :) | sudo pacman -Sy $_pkgname >> $_log 2>&1
+            (yes yes || :) | sudo pacman -Sy $_pkgname >>"$_log" 2>&1
         fi
     fi
 }
 
 usage() {
-    local _usage="
-build (kzl-linux)
+    cat <<EOF
+Usage: $SCRIPT_NAME -V | --version
+Usage: $SCRIPT_NAME -h | --help
+Usage: $SCRIPT_NAME -r <repo> -s <stage> [ -n ] [ -u ] [ --no-clean ] [ --no-check ]
+Usage: $SCRIPT_NAME -r <repo> -p <pkg> [ -n ] [ -u ] [ --no-clean ] [ --no-check ]
 
-build will build packages from scratch.
-
-Usage: build -r <repo> -s | -p <pkg> [ -n ] [ -u ] [ --no-clean ] [ --no-check ]
-
+    -V, --version               display version information and exit
     -h, --help                  display this help message and exit
     -r, --repo                  target repository (kzl, testing, ...)
     -s, --stage                 stage (0, 1(default), 2, 3)
@@ -508,9 +506,8 @@ Usage: build -r <repo> -s | -p <pkg> [ -n ] [ -u ] [ --no-clean ] [ --no-check ]
     -u, --build-only-updated    build the package only if the PKGBUILD is updated
     --no-clean                  skip cleaning up work files after build
     --no-check                  do not run the check() function in the PKGBUILD
-    -v, --version               display version information and exit
-"
-    echo "$_usage"
+
+EOF
 }
 
 ################################################################
@@ -526,20 +523,18 @@ while (($# > 0)); do
         repo="$1"
         ;;
     -s|--stage)
-        if [ -z "$single_package" ]; then
-            shift
-            stage="$1"
-        else
+        if [[ -n "$single_package" ]]; then
             error "Cannot use -s | --stage together with -p | --package" 5
         fi
+        shift
+        stage="$1"
         ;;
     -p|--package)
-        if [ -z "$stage" ]; then
-            shift
-            single_package="$1"
-        else
+        if [[ -n "$stage" ]]; then
             error "Cannot use -p | --package together with -s | --stage" 5
         fi
+        shift
+        single_package="$1"
         ;;
     -n|--no-install)
         no_install=1
@@ -565,22 +560,20 @@ prologue
 
 case $repo in
     kzl)
-        if [ -n "$stage" ]; then
+        if [[ -n "$stage" ]]; then
             case $stage in
             0)
-                updaterepo --clear -t $repo
-                pkgs=${kzl_stage0_pkgs[@]}
+                updaterepo --clear -t "$repo"
+                pkgs=("${kzl_stage0_pkgs[@]}")
                 ;;
             1)
-                pkgs=${kzl_stage1_pkgs[@]}
+                pkgs=("${kzl_stage1_pkgs[@]}")
                 ;;
             2)
-                echo -e "\033[1;33mBuilding stage 2 ($(date +%H:%M:%S))...\033[0m"
-                pkgs=${kzl_stage2_pkgs[@]}
+                pkgs=("${kzl_stage2_pkgs[@]}")
                 ;;
             3)
-                echo -e "\033[1;33mBuilding stage 3 ($(date +%H:%M:%S))...\033[0m"
-                pkgs=${kzl_stage3_pkgs[@]}
+                pkgs=("${kzl_stage3_pkgs[@]}")
                 ;;
             *)
                 error "Unknown stage \"$stage\"" 2
@@ -592,22 +585,32 @@ case $repo in
         error "Unknown repo name \"$repo\"" 3
         ;;
 esac
+log_blue "Building stage $stage ($(date +%H:%M:%S))..."
+
 
 prepare
 
-if [ ! -z "$single_package" ]; then
+if [[ -n "$single_package" ]]; then
     # Build a single package
-    echo -e "\\e[1;31mBuilding $single_package ($(date +%H:%M:%S))...\\e[0m"
-    build $single_package
+    log_magenta "Building $single_package ($(date +%H:%M:%S))..."
+    build "$single_package"
 else
     for p in ${pkgs[@]}; do
-        pkg_start_time=$(date +%s)
-        echo -e "\e[1;31mBuilding $p ($(date +%H:%M:%S))...\e[0m"
+        __pkg_start_time__=$(date +%s)
+        log_magenta "Building $p ($(date +%H:%M:%S))..."
         build $p
-        pkg_end_time=$(date +%s)
-        pkg_total_time=$((pkg_end_time-pkg_start_time))
-        echo -e "\e[1;32m$p: $(date -d@$pkg_total_time -u +%H:%M:%S) ($(date +%H:%M:%S))\e[0m"
+        __pkg_end_time__=$(date +%s)
+        __pkg_total_time__=$(($__pkg_end_time__ - $__pkg_start_time__))
+        echo -e "\e[1;32m$p: $(date -d@$__pkg_total_time__ -u +%H:%M:%S) ($(date +%H:%M:%S))\e[0m"
     done
 fi
 
 epilogue
+
+### error codes
+# 1: unknown option
+# 2: unknown stage
+# 3: unknown repo
+# 4: cannot update the PKGBUILD
+# 5: cannot use -s | --stage together with -p | --package
+# 6: unknown `updatepkg` result
