kzl-linux: pacman scripts

diff --git a/kzl-linux/pacman/scripts/updatepkg b/kzl-linux/pacman/scripts/updatepkg
--- a/kzl-linux/pacman/scripts/updatepkg
+++ b/kzl-linux/pacman/scripts/updatepkg
@@ -142,9 +142,9 @@ else
 fi
 
 if [[ $cleanbuild -gt 0 ]]; then
-    makepkg -Co || error "\`makepkg -Co\` error" 3
+    makepkg -Cdo || error "\`makepkg -Co\` error" 3
 else
-    makepkg -o || error "\`makepkg -o\` error" 3
+    makepkg -do || error "\`makepkg -o\` error" 3
 fi
 # run post_update
 info "running post_update()..."
