kzl-linux: scripts

diff --git a/kzl-linux/pacman/scripts/updatepkg b/kzl-linux/pacman/scripts/updatepkg
--- a/kzl-linux/pacman/scripts/updatepkg
+++ b/kzl-linux/pacman/scripts/updatepkg
@@ -115,7 +115,7 @@ info "Current pkgrel is $current_pkgrel"
 # run pre_update
 if have_function 'pre_update'; then
     info "running pre_update()..."
-    pre_update
+    pre_update || error "\`pre_update\` error" 4
 fi
 
 result=$(vercmp $new_version $current_version)
@@ -155,7 +155,7 @@ post_update || error "\`post_update\` error" 4
 # 1: updated
 # 2: PKGUPDATE does not exist
 # 3: makepkg -Co error
-# 4: post_update error
+# 4: pre_update or post_update error
 # 5: makepkg.conf not found
 # 6: cannot get new version
 # 7: unknow `vercmp` result
