pacman: scripts

diff --git a/kzl-linux/pacman/scripts/updaterepo b/kzl-linux/pacman/scripts/updaterepo
--- a/kzl-linux/pacman/scripts/updaterepo
+++ b/kzl-linux/pacman/scripts/updaterepo
@@ -1,5 +1,5 @@
 #!/bin/bash
-# 
+#
 # updaterepo
 #
 
@@ -10,24 +10,24 @@ PACKAGEDIR=$HOME/makepkg/packages
 ARCHIVEDIR=$HOME/makepkg/archive
 EXTENSION="zst"
 
-# options
+### options
 replace=0
 clear=0
 target=""
 
-# functions
+### functions
 # Show an INFO message
 # $1: message string
 info() {
     local _msg="$1"
-    printf '[%s] INFO: %s\n' "$script_name" "$_msg"
+    printf '\033[0;32m[%s] INFO: %s\033[0m\n' "$script_name" "$_msg"
 }
 
 # Show a WARNING message
 # $1: message string
 warning() {
     local _msg="$1"
-    printf '[%s] WARNING: %s\n' "$script_name" "$_msg" >&2
+    printf '\033[0;33m[%s] WARNING: %s\033[0m\n' "$script_name" "$_msg" >&2
 }
 
 # Show an ERROR message then exit with status
@@ -36,7 +36,7 @@ warning() {
 error() {
     local _msg="$1"
     local _error="$2"
-    printf '[%s] ERROR: %s\n' "$script_name" "$_msg" >&2
+    printf '\033[0;31m[%s] ERROR: %s\033[0m\n' "$script_name" "$_msg" >&2
     if [ "$_error" -gt 0 ]; then
         exit "$_error"
     fi
@@ -131,7 +131,7 @@ case $target in
         ;;
 esac
 
-# clear
+### clear
 if [ $clear -gt 0 ]; then
     while true; do
         read -p "Do you want to clear the repository \"$target\"? " yn
