mkimg/rpi: refactor rootfs creation and cleanup processes

diff --git a/mkimg/rpi/mkimg b/mkimg/rpi/mkimg
--- a/mkimg/rpi/mkimg
+++ b/mkimg/rpi/mkimg
@@ -66,7 +66,8 @@ common_deb_pkgs=(
 bookworm_deb_pkgs=(
     systemd-resolved
     systemd-timesyncd
-    ### raspberry pi
+)
+raspi_deb_pkgs=(
     raspberrypi-sys-mods
     raspberrypi-archive-keyring
     raspberrypi-bootloader
@@ -79,7 +80,6 @@ bookworm_deb_pkgs=(
 )
 jammy_deb_pkgs=(
     linux-firmware-raspi
-    ubuntu-raspi-settings
 )
 jammy_excluded_deb_pkgs=(
     ubuntu-advantage-tools
@@ -105,10 +105,12 @@ arg_base_img=""
 create_work_dirs() {
     info "Creating root filesystem directory: $ROOTFS_DIR"
     if [[ -d "$ROOTFS_DIR" ]]; then
-        read -p "Root filesystem directory already exists. Do you want to delete it? (Y/n) " answer
+        read -p "Root filesystem directory already exists. Do you want to remove it? (Y/n) " answer
         if [[ -z "$answer" || "$answer" == "Y" || "$answer" == "y" ]]; then
             cleanup
             trap cleanup EXIT SIGINT SIGTERM SIGKILL
+            rm -f -- "$IMG_FILE"
+            rm -rf -- "$ROOTFS_DIR"
         fi
     fi
     mkdir -p -- "$ROOTFS_DIR"
@@ -117,23 +119,44 @@ create_work_dirs() {
     mkdir -p -- "$LOG_DIR"
 }
 
+_copy_sources_list() {
+    info "Copying sources.list..."
+    cp -vf -- "sources-$distro.list" "$ROOTFS_DIR"/etc/apt/sources.list
+    sed -i -e 's|@SUITE@|'"$arg_suite"'|g' "$ROOTFS_DIR"/etc/apt/sources.list
+    if [[ "$distro" == "debian" ]]; then
+        cp -vf -- raspi.list "$ROOTFS_DIR"/etc/apt/sources.list.d/
+        sed -i -e 's|@SUITE@|'"$arg_suite"'|g' "$ROOTFS_DIR"/etc/apt/sources.list.d/raspi.list
+        wget -qO - http://archive.raspberrypi.org/debian/raspberrypi.gpg.key | gpg --dearmor | tee "$ROOTFS_DIR"/etc/apt/trusted.gpg.d/raspberrypi.gpg > /dev/null
+    fi
+    info "Done (Copied sources.list)"
+}
+
+_initialize_rootfs() {
+    info "Running initialize.sh..."
+    cp -vf -- "$SCRIPT_DIR/initialize.sh" "$ROOTFS_DIR"
+    chroot_run "$ROOTFS_DIR" "/initialize.sh" || error "Failed to run initialize.sh" 9
+    rm -vf -- "$ROOTFS_DIR/initialize.sh"
+    info "Done (Ran initialize.sh)"
+}
+
 debootstrap_rootfs() {
     local _deb_pkglist="${arg_suite}_deb_pkglist.txt"
-    touch -- "$_deb_pkglist"
+    local _ls_R="${arg_suite}-ls_R.txt"
+    sudo -u "${SUDO_USER:-root}" touch -- "$_deb_pkglist" "$_ls_R"
 
-    info "Creating the list of installed deb packages..."
-    debootstrap \
-        --print-debs \
-        --arch=arm64 \
-        --include="$(IFS=',' echo "${deb_pkgs[*]}")" \
-        --exclude="$(IFS=',' echo "${excluded_deb_pkgs[*]}")" \
-        --components=main,restricted,universe \
-        --merged-usr \
-        "$arg_suite" \
-        "$ROOTFS_DIR" \
-        "$mirror" \
-        2> /dev/null | sed 's/ /\n/g' | LC_ALL=C sort -u > "$_deb_pkglist" || warn "Failed to create a list of installed deb packages"
-    info "Done (Created the list of installed deb packages)"
+    # info "Creating the list of installed deb packages..."
+    # debootstrap \
+    #     --print-debs \
+    #     --arch=arm64 \
+    #     --include="$(IFS=',' echo "${deb_pkgs[*]}")" \
+    #     --exclude="$(IFS=',' echo "${excluded_deb_pkgs[*]}")" \
+    #     --components=main,restricted,universe \
+    #     --merged-usr \
+    #     "$arg_suite" \
+    #     "$ROOTFS_DIR" \
+    #     "$mirror" \
+    #     2> /dev/null | sed 's/ /\n/g' | LC_ALL=C sort -u > "$_deb_pkglist" || warn "Failed to create a list of installed deb packages"
+    # info "Done (Created the list of installed deb packages)"
 
     info "Debootstrapping \"$ROOTFS_DIR/\": ${deb_pkgs[*]}"
     debootstrap \
@@ -147,13 +170,51 @@ debootstrap_rootfs() {
         "$ROOTFS_DIR" \
         "$mirror" \
         2>&1 | tee "$LOG_DIR/debootstrap.log" || error "Failed to debootstrap (stage 1) rootfs" 5
+
+    _copy_sources_list
+
     chroot_setup "$ROOTFS_DIR" || error "Failed to setup chroot environment" 6
     chroot_run "$ROOTFS_DIR" /debootstrap/debootstrap --second-stage || error "Failed to debootstrap (stage 2) rootfs" 7
-    info "Done (Configured rootfs)"
+    case "$distro" in
+        debian)
+            chroot_run "$ROOTFS_DIR" bash -c "apt-get update && apt-get install -y ${raspi_deb_pkgs[@]}" || error "Failed to install raspi packages" 7
+            ;;
+        ubuntu)
+            # Fix: check if ubuntu-raspi-settings is able to be installed by debootstrap
+            chroot_run "$ROOTFS_DIR" bash -c "apt-get update && apt-get install -y ubuntu-raspi-settings" || error "Failed to install raspi packages" 7
+            ;;
+    esac
+    chroot_run "$ROOTFS_DIR" dpkg-query -W -f='${Package}\n' > "$_deb_pkglist" || warn "Failed to create a list of installed deb packages"
+    chroot_run "$ROOTFS_DIR" ls -R / > "$_ls_R" || warn "Failed to get ls-R"
+    _initialize_rootfs
+    chroot_teardown
+
+    rm -vrf "$ROOTFS_DIR"/dev/*
+    rm -vrf "$ROOTFS_DIR"/tmp/*
+    rm -vrf "$ROOTFS_DIR"/usr/share/doc/*
+    rm -vrf "$ROOTFS_DIR"/var/lib/apt/lists/*
+    rm -vrf "$ROOTFS_DIR"/var/log/*
+    rm -vrf "$ROOTFS_DIR"/var/cache/apt/archives/*.deb
+    rm -vrf "$ROOTFS_DIR"/var/tmp/*
+
+    info "Done (Debootstrapped rootfs)"
 }
 
 mmdebstrap_rootfs() {
-    info "Debootstrapping \"$ROOTFS_DIR/\": ${deb_pkgs[*]}"
+    local _deb_pkglist="${arg_suite}_deb_pkglist.txt"
+    local _ls_R="${arg_suite}-ls_R.txt"
+    sudo -u "${SUDO_USER:-root}" touch -- "$_deb_pkglist" "$_ls_R"
+
+    info "mmdebstrapping \"$ROOTFS_DIR/\": ${deb_pkgs[*]}"
+
+    case "$distro" in
+        debian)
+            deb_pkgs+=("${raspi_deb_pkgs[@]}")
+            ;;
+        ubuntu)
+            deb_pkgs+=(ubuntu-raspi-settings)
+            ;;
+    esac
     mmdebstrap \
         --variant=- \
         --mode=root \
@@ -165,35 +226,17 @@ mmdebstrap_rootfs() {
         "$ROOTFS_DIR" \
         "${mirrors[@]}" \
         2>&1 | tee "$LOG_DIR/mmdebstrap.log" || error "Failed to mmdebstrap rootfs" 8
-    info "Done (Configured rootfs)"
 
-    info "Copying sources.list..."
-    cp -vf -- "sources-$distro.list" "$ROOTFS_DIR"/etc/apt/sources.list
-    sed -i -e 's|@SUITE@|'"$arg_suite"'|g' "$ROOTFS_DIR"/etc/apt/sources.list
-    if [[ "$distro" == "debian" ]]; then
-        cp -vf -- raspi.list "$ROOTFS_DIR"/etc/apt/sources.list.d/
-        sed -i -e 's|@SUITE@|'"$arg_suite"'|g' "$ROOTFS_DIR"/etc/apt/sources.list.d/raspi.list
-        wget -qO - http://archive.raspberrypi.org/debian/raspberrypi.gpg.key | gpg --dearmor | tee "$ROOTFS_DIR"/etc/apt/trusted.gpg.d/raspberrypi.gpg > /dev/null
-    fi
-    info "Done (Copied sources.list)"
+    _copy_sources_list
 
     chroot_setup "$ROOTFS_DIR" || error "Failed to setup chroot environment" 6
-
-    info "Removing excluded packages: ${excluded_deb_pkgs[*]}"
     chroot_run "$ROOTFS_DIR" apt-get remove -y --purge "${excluded_deb_pkgs[@]}" || warn "Failed to remove excluded packages"
-    info "Done (Removed excluded packages)"
-
-    info "Creating the list of installed deb packages..."
-    chroot_run "$ROOTFS_DIR" dpkg-query -W -f='${Package}\n' > "${arg_suite}_deb_pkglist.txt" || warn "Failed to create a list of installed deb packages"
-    info "Done (Created the list of installed deb packages)"
-
-    info "Running initialize.sh..."
-    cp -vf -- "$SCRIPT_DIR/initialize.sh" "$ROOTFS_DIR"
-    chroot_run "$ROOTFS_DIR" "/initialize.sh" || error "Failed to run initialize.sh" 9
-    rm -vf -- "$ROOTFS_DIR/initialize.sh"
-    info "Done (Ran initialize.sh)"
-
+    chroot_run "$ROOTFS_DIR" dpkg-query -W -f='${Package}\n' > "$_deb_pkglist" || warn "Failed to create a list of installed deb packages"
+    chroot_run "$ROOTFS_DIR" ls -R / > "$_ls_R" || warn "Failed to get ls-R"
+    _initialize_rootfs
     chroot_teardown
+
+    info "Done (mmdebstrapped rootfs)"
 }
 
 create_base_rootfs_tarball() {
@@ -280,14 +323,10 @@ cleanup() {
     loop_teardown "$loop_device"
     info "Done (Unmounted work directories)"
 
-    info "Removing work directories..."
     mount | grep -q "$ROOTFS_DIR"
     if (( $? == 0 )); then
         error "There are mount points under $WORK_DIR, please unmount it manually" 255
     fi
-    rm -f -- "$IMG_FILE"
-    rm -rf -- "$ROOTFS_DIR"
-    info "Done (Removed work directories)"
 
     trap - EXIT SIGINT SIGTERM SIGKILL
 }
@@ -376,8 +415,8 @@ prologue
 
 if [[ -z "$arg_base_img" ]]; then
     create_work_dirs
-    # debootstrap_rootfs
-    mmdebstrap_rootfs
+    debootstrap_rootfs
+    # mmdebstrap_rootfs
     create_base_rootfs_tarball
 elif [[ -f "$arg_base_img" ]]; then
         cp "$arg_base_img" "$IMG_FILE"
