mkrootfs: first version

diff --git a/mkrootfs/mkrootfs b/mkrootfs/mkrootfs
--- a/mkrootfs/mkrootfs
+++ b/mkrootfs/mkrootfs
@@ -10,23 +10,23 @@ set -o pipefail
 
 umask 0022
 
-unset __DEBUG__
-__DEBUG__=1
-
 SCRIPT_NAME="$(basename "$0")"
 SCRIPT_PATH="$0"
 SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
 
 ################################################################################
 
-### checks
-check_root
+unset __DEBUG__
+__DEBUG__=1
 
 ### libraries
 . "$SCRIPT_DIR"/lib/log.sh
 . "$SCRIPT_DIR"/lib/utils.sh
 . "$SCRIPT_DIR"/lib/loop.sh
 . "$SCRIPT_DIR"/lib/chroot.sh
+
+### checks
+check_root
 
 ### constants and variables
 declare -r TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
@@ -35,6 +35,7 @@ declare -r WORK_DIR="/tmp/mkrootfs_$TIMESTAMP"
 declare -r ROOTFS_DIR="$WORK_DIR/rootfs"
 declare -r LOG_DIR="$WORK_DIR/log"
 
+declare -r ETC_DIR="$SCRIPT_DIR/etc"
 declare -r PKGLIST_DIR="$SCRIPT_DIR/pkglist"
 
 declare -r DEBIAN_MIRROR="http://deb.debian.org/debian"
@@ -42,7 +43,25 @@ declare -r UBUNTU_MIRROR="http://us.archive.ubuntu.com/ubuntu/"
 # declare -r UBUNTU_MIRROR="https://mirror.arizona.edu/ubuntu/"
 declare -r UBUNTU_PORT_MIRROR="http://ports.ubuntu.com/ubuntu-ports/"
 
+common_deb_pkgs=(
+    bash-completion
+    zsh zsh-autosuggestions zsh-syntax-highlighting
+    nano
+    openssh-server
+    curl wget git
+    # screen tmux
+)
+ubuntu_excluded_deb_pkgs=(
+    cron
+    ubuntu-advantage-tools
+    ubuntu-minimal
+    ubuntu-pro-client
+    ubuntu-pro-client-l10n
+)
+
 distro=""
+architecture=""
+debian_mirror=""
 ubuntu_mirror=""
 mirror=""
 mirrors=()
@@ -51,11 +70,10 @@ deb_pkgs=()
 excluded_deb_pkgs=()
 
 ### options and arguments
-arg_architecture="amd64"
+arg_platform="pc"
 arg_suite="noble"
 
 ### functions
-
 cleanup() {
     set +e
     info "Cleaning up..."
@@ -82,27 +100,24 @@ create_work_dirs() {
     if [[ -d "$WORK_DIR" ]]; then
         error "Working directory $WORK_DIR already exists" 1
     fi
+    mkdir -p -- "$WORK_DIR"
+    mkdir -p -- "$ROOTFS_DIR"
+    mkdir -p -- "$LOG_DIR"
+    if [[ ! -d "$PKGLIST_DIR" ]]; then
+        mkdir -p -- "$PKGLIST_DIR"
+        chown ${SUDO_UID:-0}:${SUDO_GID:-0} -- "$PKGLIST_DIR"
+    fi
     info "Done (Created root filesystem directory)"
 }
 
-_setup_sources_list() {
-    info "Setting up sources.list..."
-    cp -vf -- "$distro.sources" "$ROOTFS_DIR/etc/apt/sources.list.d/"
-    if [[ "$arg_architecture" == "amd64" ]]; then
-        cp -vf -- "$distro.sources" "$ROOTFS_DIR/etc/apt/sources.list.d/"
-    elif [[ "$arg_architecture" == "arm64" ]]; then
-    fi
-    info "Done (Set up sources.list)"
-}
-
 debootstrap_rootfs() {
-    local _deb_pkglist_file="$PKGLIST_DIR/${arg_suite}_deb_pkglist.txt"
-    sudo -u "${SUDO_USER:-root}" touch -- "$_deb_pkglist_file"
+    local -r _deb_pkg_to_install="$PKGLIST_DIR/$arg_platform-$arg_suite-deb_to_install.txt"
+    sudo -u "${SUDO_USER:-root}" touch -- "$_deb_pkg_to_install"
 
     info "Creating the list of deb packages to be installed..."
     debootstrap \
         --print-debs \
-        --arch "$arg_architecture" \
+        --arch "$architecture" \
         --include="$(IFS=',' echo "${deb_pkgs[*]}")" \
         --exclude="$(IFS=',' echo "${excluded_deb_pkgs[*]}")" \
         --components=main,restricted,universe \
@@ -110,38 +125,133 @@ debootstrap_rootfs() {
         "$arg_suite" \
         "$ROOTFS_DIR" \
         "$mirror" \
-        2> /dev/null | sed 's/ /\n/g;/^$/d' | LC_ALL=C sort -n > "$_deb_pkglist_file" || warn "Failed to creating the list of deb packages to be installed"
+        2> /dev/null | sed 's/ /\n/g' | LC_ALL=C sort -n  | sed '/^$/d' > "$_deb_pkg_to_install" || warn "Failed to creating the list of deb packages to be installed"
     info "Done (Created the list of installed deb packages)"
 
     info "Debootstrapping \"$ROOTFS_DIR/\": ${deb_pkgs[*]}"
     local _foreign=""
-    if [[ "$arg_architecture" != "$(dpkg --print-architecture)" ]]; then
+    if [[ "$architecture" != "$(dpkg --print-architecture)" ]]; then
         _foreign="--foreign"
     fi
     debootstrap \
-        --arch "$arg_architecture" \
+        --arch "$architecture" \
         --include="$(IFS=',' echo "${deb_pkgs[*]}")" \
         --exclude="$(IFS=',' echo "${excluded_deb_pkgs[*]}")" \
         --components=main,restricted,universe \
         --merged-usr \
-        "$_foreign" \
+        $_foreign \
         "$arg_suite" \
         "$ROOTFS_DIR" \
         "$mirror" \
         2>&1 | tee "$LOG_DIR"/debootstrap.log || error "Failed to debootstrap rootfs" 2
+    if [[ -n "$_foreign" ]]; then
+        chroot "$ROOTFS_DIR" /debootstrap/debootstrap --second-stage || error "Failed to debootstrap (stage 2) rootfs" 3
+    fi
+    info "Done (Debootstrapped rootfs)"
+}
 
-    _setup_sources_list
+# mmdebstrap_rootfs() {
+#     local _deb_pkglist="${arg_suite}_deb_pkglist.txt"
+#     sudo -u "${SUDO_USER:-root}" touch -- "$_deb_pkglist"
+
+#     info "mmdebstrapping \"$ROOTFS_DIR/\": ${deb_pkgs[*]}"
+#     mmdebstrap \
+#         --variant=- \
+#         --mode=root \
+#         --format=directory \
+#         --dpkgopt='path-exclude=/usr/share/doc/*' \
+#         --include="$(IFS=',' echo "${deb_pkgs[*]}")" \
+#         --architectures=arm64 \
+#         "$arg_suite" \
+#         "$ROOTFS_DIR" \
+#         "${mirrors[@]}" \
+#         2>&1 | tee "$LOG_DIR/mmdebstrap.log" || error "Failed to mmdebstrap rootfs" 8
+#     info "Done (mmdebstrapped rootfs)"
+# }
+
+configure_rootfs() {
+    local -r _deb_pkg_installed="$PKGLIST_DIR/$arg_platform-$arg_suite-deb_installed.txt"
+    sudo -u "${SUDO_USER:-root}" touch -- "$_deb_pkg_installed"
+
+    info "Configuring rootfs..."
+
+    info "  Setting up sources.list..."
+    case "$arg_platform-$distro" in
+        pc-debian|pc-ubuntu)
+            sed "s|@SUITE@|$arg_suite|g" "$ETC_DIR/$distro.sources" > "$ROOTFS_DIR/etc/apt/sources.list.d/$distro.sources"
+            ;;
+        raspberrypi-debian)
+            sed "s|@SUITE@|$arg_suite|g" "$ETC_DIR/debian.sources" > "$ROOTFS_DIR/etc/apt/sources.list.d/debian.sources"
+            sed "s|@SUITE@|$arg_suite|g" "$ETC_DIR/raspi.sources" > "$ROOTFS_DIR/etc/apt/sources.list.d/raspi.sources"
+            wget -qO "$ROOTFS_DIR/etc/apt/trusted.gpg.d/raspberrypi.gpg.key" http://archive.raspberrypi.org/debian/raspberrypi.gpg.key
+            ;;
+        raspberrypi-ubuntu)
+            mkdir -p -- "$ROOTFS_DIR/etc/apt/sources.list.d"
+            sed "s|@SUITE@|$arg_suite|g" "$ETC_DIR/ubuntu-ports.sources" > "$ROOTFS_DIR/etc/apt/sources.list.d/ubuntu-ports.sources"
+            ;;
+        *)
+            error "Unsupported platform-distro pair: $arg_platform-$distro" 1
+            ;;
+    esac
+    if [[ -f "$ROOTFS_DIR/etc/apt/sources.list" ]]; then
+        mv -v -- "$ROOTFS_DIR/etc/apt/sources.list" "$ROOTFS_DIR/etc/apt/sources.list.bak"
+    fi
+    info "  Done (Set up sources.list)"
+
+    info "  Running chroot configuration..."
+    chroot_setup "$ROOTFS_DIR" || error "Failed to setup chroot environment" 3
+    # run initialize.sh
+    cp -vf -- "$SCRIPT_DIR/initialize.sh" "$ROOTFS_DIR"
+    chroot_run "$ROOTFS_DIR" "/initialize.sh" || error "Failed to run initialize.sh" 3
+    rm -vf -- "$ROOTFS_DIR/initialize.sh"
+    # get installed deb packages
+    chroot_run "$ROOTFS_DIR" dpkg-query -W -f='${Package}\n' > "$_deb_pkg_installed" || warn "Failed to create a list of installed deb packages"
+    chroot_teardown
+    info "  Done (Chroot configuration)"
+
+    info "  Cleaning up rootfs..."
+    rm -vrf "$ROOTFS_DIR"/dev/*
+    rm -vrf "$ROOTFS_DIR"/run/*
+    rm -vrf "$ROOTFS_DIR"/tmp/*
+    rm -vrf "$ROOTFS_DIR"/usr/share/doc/*
+    rm -vrf "$ROOTFS_DIR"/var/cache/apt/archives/*.deb
+    rm -vrf "$ROOTFS_DIR"/var/cache/ldconfig/*
+    rm -vrf "$ROOTFS_DIR"/var/lib/apt/lists/*
+    rm -vrf "$ROOTFS_DIR"/var/log/*
+    rm -vrf "$ROOTFS_DIR"/var/tmp/*
+    info "  Done (Cleaned up rootfs)"
+
+    info "Done (Configured rootfs)"
+}
+
+create_rootfs_tarball() {
+    local -r _name="rootfs-$arg_platform-$distro-$arg_suite-$TIMESTAMP.tar.zst"
+    info "Creating base rootfs tarball..."
+    tar -v \
+        --zstd \
+        --xattrs --acls \
+        --numeric-owner \
+        --transform='s|^./||' \
+        -cpf "$SCRIPT_DIR/$_name" \
+        -C "$ROOTFS_DIR" . \
+        2>&1 > "$LOG_DIR/tar.log" || error "Failed to create base rootfs tarball" 4
+    chown ${SUDO_UID:-0}:${SUDO_GID:-0} "$SCRIPT_DIR/$_name"
+    info "Done (Created base rootfs tarball)"
 }
 
 usage() {
     cat << EOF
 
 Usage: $SCRIPT_NAME -h | --help
-Usage: $SCRIPT_NAME [ -a | --architecture <arch> ] -s | --suite <suite>
+Usage: $SCRIPT_NAME [ -p | --platform <platform> ] -s | --suite <suite>
 
     -h, --help                      print this help message and exit
-    -a, --architecture <arch>       specify the image architecture (amd64, arm64)
-    -s, --suite <suite>             specify the distribution suite (bookworm, jammy, noble, questing)
+    -p, --platform <platform>       specify the platform
+                                    supported platforms: pc, raspberrypi
+                                    default: pc
+    -s, --suite <suite>             specify the distribution suite
+                                    supported suites: bookworm, trixie, jammy, noble, questing
+                                    default: noble
 EOF
 }
 
@@ -153,9 +263,9 @@ while (( $# > 0 )); do
         usage
         exit 0
         ;;
-    -a | --architecture)
+    -p | --platform)
         shift
-        arg_architecture="$1"
+        arg_platform="$1"
         ;;
     -s | --suite)
         shift
@@ -163,44 +273,64 @@ while (( $# > 0 )); do
         ;;
     *)
         usage
-        error "Unknown option: $1" 127
+        error "Unknown option: $1" 128
         ;;
     esac
     shift
 done
 
-case "$arg_architecture" in
-    amd64)
+case "$arg_platform" in
+    pc)
+        architecture="amd64"
+        debian_mirror="$DEBIAN_MIRROR"
         ubuntu_mirror="$UBUNTU_MIRROR"
         ;;
-    arm64)
+    raspberrypi)
+        architecture="arm64"
+        debian_mirror="$DEBIAN_MIRROR"
         ubuntu_mirror="$UBUNTU_PORT_MIRROR"
         ;;
     *)
         usage
-        error "Unsupported architecture \"$arg_architecture\"." 2
+        error "Unsupported platform \"$arg_platform\"." 1
         ;;
 esac
 
 case "$arg_suite" in
-    bookworm)
+    bookworm|trixie)
         distro="debian"
-        mirror="$DEBIAN_MIRROR"
+        mirror="$debian_mirror"
+        deb_pkgs=("${common_deb_pkgs[@]}")
         ;;
-    jammy)
+    jammy|noble|questing)
         distro="ubuntu"
         mirror="$ubuntu_mirror"
-        ;;
-    noble)
-        distro="ubuntu"
-        mirror="$ubuntu_mirror"
-        ;;
-    questing)
-        distro="ubuntu"
-        mirror="$ubuntu_mirror"
+        deb_pkgs=("${common_deb_pkgs[@]}")
+        excluded_deb_pkgs=("${ubuntu_excluded_deb_pkgs[@]}")
         ;;
     *)
         usage
-        error "Unsupported distribution \"$arg_suite\"." 2
+        error "Unsupported distribution \"$arg_suite\"." 1
         ;;
 esac
+
+################################################################################
+
+prologue
+
+create_work_dirs
+debootstrap_rootfs
+# mmdebstrap_rootfs
+configure_rootfs
+create_rootfs_tarball
+cleanup
+
+epilogue
+
+### error codes
+# 1: general error
+# 2: debootstrap error
+# 3: chroot error
+# 4: tar error
+# 128: unknown option
+# 255: must be run as root
