ubuntu: mkiso

diff --git a/ubuntu/mkiso/mkiso b/ubuntu/mkiso/mkiso
--- a/ubuntu/mkiso/mkiso
+++ b/ubuntu/mkiso/mkiso
@@ -90,12 +90,31 @@ EOF
 }
 
 debootstrap_rootfs() {
-    local _pkg_list=("$@")
+    local -a _pkg_list=("$@")
+    local -a _pkg_exclude=(
+        "ubuntu-minimal"
+        "ubuntu-pro-client"
+        "ubuntu-pro-client-l10n"
+    )
 
     info "Debootstrapping \"$ROOTFS_DIR/\": ${_pkg_list[*]}"
     # debootstrap
+    info "Creating a list of installed deb packages..."
     debootstrap \
-        --include="$(IFS=','; echo "${_pkg_list[*]}")" \
+        --include="$(IFS=',' echo "${_pkg_list[*]}")" \
+        --exclude="$(IFS=',' echo "${_pkg_exclude[*]}")" \
+        --components=main,restricted,universe \
+        --merged-usr \
+        --print-debs \
+        "$debootstrap_suite" \
+        "$ROOTFS_DIR"/tmp \
+        "$UBUNTU_MIRROR" \
+        > "$ISOFS_DIR"/deb_pkglist.txt 2> /dev/null || warn "Failed to creating a list of installed deb packages"
+    info "Done"
+
+    debootstrap \
+        --include="$(IFS=',' echo "${_pkg_list[*]}")" \
+        --exclude="$(IFS=',' echo "${_pkg_exclude[*]}")" \
         --components=main,restricted,universe \
         --merged-usr \
         "$debootstrap_suite" \
@@ -109,23 +128,11 @@ debootstrap_rootfs() {
     fi
     info "Done"
 
-    info "Creating a list of installed deb packages..."
-    debootstrap \
-        --include="$(IFS=','; echo "${_pkg_list[*]}")" \
-        --components=main,restricted,universe \
-        --merged-usr \
-        --print-debs \
-        "$debootstrap_suite" \
-        "$ROOTFS_DIR"/tmp \
-        "$UBUNTU_MIRROR" \
-        > "$ISOFS_DIR"/deb_pkglist.txt 2> /dev/null || warn "Failed to creating a list of installed deb packages"
-    info "Done"
-
     info "Configuring rootfs..."
     install -d -m 1777 -- "$ROOTFS_DIR"/tmp
     chroot_setup "$ROOTFS_DIR" || error "Failed to setup chroot environment" 6
-    chroot_run "$ROOTFS_DIR" systemctl enable systemd-networkd.service >"$LOG_DIR"/systemd-networkd.log 2>&1 || error "Failed to enable systemd-networkd" 6
-    chroot_run "$ROOTFS_DIR" apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y >"$LOG_DIR"/apt.log 2>&1 || error "Failed to run apt" 6
+    chroot_run "$ROOTFS_DIR" systemctl enable systemd-networkd.service > "$LOG_DIR"/systemd-networkd.log 2>&1 || error "Failed to enable systemd-networkd" 6
+    chroot_run "$ROOTFS_DIR" apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y && apt-get autoremove --purge -y > "$LOG_DIR"/apt.log 2>&1 || error "Failed to run apt" 6
     chroot_run "$ROOTFS_DIR" ldconfig
     chroot_teardown
     info "Done"
