pacman/scripts: fit new template

diff --git a/pacman/scripts/updatepkg b/pacman/scripts/updatepkg
--- a/pacman/scripts/updatepkg
+++ b/pacman/scripts/updatepkg
@@ -10,34 +10,16 @@ set -o pipefail
 
 umask 0022
 
-SCRIPT_NAME="$(basename "$0")"
-SCRIPT_PATH="$(realpath --no-symlinks "$0")"
-SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
+declare -r SCRIPT_NAME="$(basename "$0")"
+declare -r SCRIPT_PATH="$(realpath --no-symlinks "$0")"
+declare -r SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
+declare -ar SCRIPT_INVOCATION=("$@")
 
 ################################################################################
 
-### libraries
+### bash utils
 . "$SCRIPT_DIR"/lib/log.sh
-if [[ -f "/etc/makepkg.conf" ]]; then
-    . /etc/makepkg.conf
-elif [[ -f "/opt/etc/makepkg.conf" ]]; then
-    . /opt/etc/makepkg.conf
-else
-    error "makepkg.conf NOT found" 4
-fi
-. PKGBUILD || error "Failed get package information from PKGBUILD" 2
-unset new_version srcdir build_system pre_update post_update
-. PKGUPDATE || error "Failed to get new version from PKGUPDATE" 3
-
-### constants & variables
-declare -r PKGBUILDDIR="$(pwd)"
-declare -r PKGBUILD_FILE_PATH="$(realpath PKGBUILD)"
-# PGP_KEY_SERVER="hkps://keyserver.ubuntu.com"
-# PGP_KEY_SERVER="hkps://keys.openpgp.org"
-# PGP_KEY_SERVER="hkps://pgp.mit.edu"
-declare -r CURRENT_VERSION=$(grep -oP 'pkgver=\K.+$' PKGBUILD | sed 's/\.g.*//')
-declare -r -i CURRENT_PKGREL=$(grep -oP 'pkgrel=\K\d+$' PKGBUILD)
-declare -r -i NEW_PKGREL=$(($CURRENT_PKGREL + 1))
+. "$SCRIPT_DIR"/lib/utils.sh
 
 ### options and arguments
 opt_syncdeps='-d'
@@ -45,25 +27,7 @@ opt_cleanbuild='-C'
 declare -i opt_increase=0
 declare -i opt_increase_only=0
 
-### functions
-
-update_pkgbuild() {
-    info "PKGBUILD updated: $CURRENT_VERSION-$CURRENT_PKGREL => $NEW_VERSION-1"
-    sed -i \
-        -e "/^pkgver=/c\\pkgver=$new_version" \
-        -e "/^pkgrel=/c\\pkgrel=1" \
-        "$PKGBUILD_FILE_PATH"
-    info "Running \`updpkgsums\`..."
-    updpkgsums || error "\`updpkgsums\` error" 4
-    info "Done (Running \`updpkgsums\`)"
-    # force cleanbuild
-    opt_cleanbuild='-C'
-}
-
-update_pkgrel() {
-    info "pkgrel increased: $CURRENT_PKGREL => $NEW_PKGREL"
-    sed -i "/^pkgrel=/c\\pkgrel=$NEW_PKGREL" "$PKGBUILD_FILE_PATH"
-}
+################################################################################
 
 usage() {
     cat << EOF
@@ -82,8 +46,6 @@ Usage: $SCRIPT_NAME -I
 
 EOF
 }
-
-################################################################################
 
 while (( $# > 0 )); do
     case "$1" in
@@ -110,6 +72,53 @@ while (( $# > 0 )); do
     esac
     shift
 done
+readonly opt_syncdeps
+readonly opt_cleanbuild
+readonly opt_increase
+readonly opt_increase_only
+
+################################################################################
+
+### constants & variables
+declare -r PKGBUILDDIR="$(pwd)"
+declare -r PKGBUILD_FILE_PATH="$(realpath PKGBUILD)"
+# PGP_KEY_SERVER="hkps://keyserver.ubuntu.com"
+# PGP_KEY_SERVER="hkps://keys.openpgp.org"
+# PGP_KEY_SERVER="hkps://pgp.mit.edu"
+declare -r CURRENT_VERSION=$(grep -oP 'pkgver=\K.+$' PKGBUILD | sed 's/\.g.*//')
+declare -r -i CURRENT_PKGREL=$(grep -oP 'pkgrel=\K\d+$' PKGBUILD)
+declare -r -i NEW_PKGREL=$(($CURRENT_PKGREL + 1))
+
+### libraries
+. "$SCRIPT_DIR"/lib/log.sh
+if [[ -f "/etc/makepkg.conf" ]]; then
+    . /etc/makepkg.conf
+elif [[ -f "/opt/etc/makepkg.conf" ]]; then
+    . /opt/etc/makepkg.conf
+else
+    error "makepkg.conf NOT found" 4
+fi
+. PKGBUILD || error "Failed get package information from PKGBUILD" 2
+unset new_version srcdir build_system pre_update post_update
+. PKGUPDATE || error "Failed to get new version from PKGUPDATE" 3
+
+### functions
+update_pkgbuild() {
+    info "PKGBUILD updated: $CURRENT_VERSION-$CURRENT_PKGREL => $new_version-1"
+    sed -i \
+        -e "/^pkgver=/c\\pkgver=$new_version" \
+        -e "/^pkgrel=/c\\pkgrel=1" \
+        "$PKGBUILD_FILE_PATH"
+    info "Running \`updpkgsums\`..."
+    updpkgsums || error "\`updpkgsums\` error" 4
+    # force cleanbuild
+    opt_cleanbuild='-C'
+}
+
+update_pkgrel() {
+    info "pkgrel increased: $CURRENT_PKGREL => $NEW_PKGREL"
+    sed -i "/^pkgrel=/c\\pkgrel=$NEW_PKGREL" "$PKGBUILD_FILE_PATH"
+}
 
 ################################################################################
 
@@ -140,11 +149,10 @@ fi
 if declare -F 'pre_update' > /dev/null; then
     info "Running pre_update()..."
     pre_update || error "\`pre_update\` error" 4
-    info "Done (Running pre_update())"
 fi
 
 # receive key id
-if (( ${#validpgpkeys[@]} )); then
+if (( ${#validpgpkeys[@]} > 0 )); then
     if ! gpg --list-keys --with-colons "${validpgpkeys[@]}" > /dev/null 2>&1; then
         # gpg --keyserver "$PGP_KEY_SERVER" --recv-keys "${validpgpkeys[@]}" || error "\`gpg --recv-keys\` error" 4
         gpg --recv-keys "${validpgpkeys[@]}" || error "\`gpg --recv-keys\` error" 4
@@ -154,7 +162,6 @@ fi
 info "Running \`makepkg -o\`..."
 cd "$PKGBUILDDIR"
 makepkg "$opt_cleanbuild" "$opt_syncdeps" -o --noconfirm || error "\`makepkg -o\` error" 5
-info "Done (Running \`makepkg -o\`)"
 
 # get build options
 info "Getting build options..."
@@ -199,14 +206,12 @@ if [[ "$build_system" == "autoconf" || "$build_system" == "meson" || "$build_sys
 else
     info "Unknown build_system or it is not defined, skipping auto getting build options"
 fi
-info "Done (Getting build options)"
 
 # run post_update
 cd "$PKGBUILDDIR"
 if declare -F 'post_update' > /dev/null; then
     info "Running post_update()..."
     post_update || error "\`post_update\` error" 4
-    info "Done (Running post_update())"
 fi
 
 log_cyan "Successfully updated PKGBUILD"
